name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-files
        path: dist/
        retention-days: 30

    # Uncomment and configure the following step for automatic deployment
    # - name: Deploy to server
    #   if: github.ref == 'refs/heads/main'
    #   run: |
    #     # Add your deployment commands here
    #     # Example: rsync, scp, or API calls to your hosting provider
    #     echo "Deploy to magnadashboard.clxdigital.ro"